/* eslint-disable import/no-anonymous-default-export */
import checkoutFormModel from "./checkoutFormModel";
const {
  formField: {
    email,
    jobName,
    jobNumber,
    productionCompanyInfo,
    productionCompanyName,
    billingAddress,
    billingCity,
    billingState,
    billingZipCode,
    billingPhoneNumber,
    emailAddressToReceiveInvoices,
    nameOfAuthorizedSignatory,
    titleOfAuthorizedSignatory,
    cardholderInfo,
    cardholderName,
    cardholderDriversLicenseNumber,
    cardholderDriversLicenseState,
    cardholderDriversLicenseExpiry,
    creditCardInfo,
    accountType,
    issuingBank,
    cardType,
    cardNumber,
    expirationDate,
    cvv,
    fourDigitCID,
    shippingDetails,
    shippingAccount,
    shippingAccountNumber,
  },
} = checkoutFormModel;

export default {
  [email.name]: "",
  [jobName.name]: "",
  [jobNumber.name]: "",
  [productionCompanyInfo.name]: "",
  [productionCompanyName.name]: "",
  [billingAddress.name]: "",
  [billingCity.name]: "",
  [billingState.name]: "",
  [billingZipCode.name]: "",
  [billingPhoneNumber.name]: "",
  [emailAddressToReceiveInvoices.name]: "",
  [nameOfAuthorizedSignatory.name]: "",
  [titleOfAuthorizedSignatory.name]: "",
  [cardholderInfo.name]: "",
  [cardholderName.name]: "",
  [cardholderDriversLicenseNumber.name]: "",
  [cardholderDriversLicenseState.name]: "",
  [cardholderDriversLicenseExpiry.name]: "",
  [creditCardInfo.name]: "",
  [accountType.name]: "",
  [issuingBank.name]: "",
  [cardType.name]: "",
  [cardNumber.name]: "",
  [expirationDate.name]: "",
  [cvv.name]: "",
  [fourDigitCID.name]: "",
  buyers: [
    {
      name: "",
      title: "",
      phone: "",
      email: "",
    },
  ],
  [shippingDetails.name]: "",
  [shippingAccount.name]: "",
  [shippingAccountNumber.name]: "",
};
