const vendors = [
  "A1 Medical",
  "Advanced Liquidators",
  "Air Designs",
  "Air Hollywood",
  "Alley Cats",
  "Amazon",
  "Astek",
  "Athletic Room",
  "Auditorium Props",
  "Avon",
  "Bill Ferrell",
  "Castex",
  "Cinema Vehicles",
  "Dangling Carrot",
  "Dazian",
  "Earl Hays Press",
  "EC Props",
  "Faux Library Studio Props",
  "Form Décor",
  "Galpin Studio Rentals",
  "Gavrieli",
  "Green Set, Inc.",
  "Heaven or Las Vegas",
  "Herc",
  "History 4 Hire",
  "Hollywood Cinema Arts, Inc. ",
  "Hollywood Studio Gallery",
  "Hollywood Trophy",
  "Hot Bricks",
  "Independent Studio Services",
  "Jackson Shrub",
  "JC Backings",
  "LCW Props",
  "Lennie Marvin Enterprises, Inc.",
  "Lino City",
  "Little Bohemia",
  "Modernica Props",
  "NEST Studio Rentals",
  "Nights of Neon",
  "Objects",
  "Omega Cinema Props",
  "Pacific Studios",
  "Paramount Pictures (Sign Shop)",
  "Pinacoteca Picture Props",
  "Practical Props",
  "Premiere Props",
  "Prop Studios West",
  "Pulp Art Surfaces",
  "Quixote",
  "RC Vintage",
  "Recycled Movie Sets",
  "Rose Brand",
  "Schmidli",
  "Set Life",
  "Set Stuff",
  "Spellman Desk Co",
  "SPFX Unlimited",
  "Target Props",
  "Town and Country Event Rentals",
  "Universal Studios",
  "Vision Scenery",
  "Vineland Nusery",
  "Warner Bros",
  "West Coast Backings",
  "Zany Graphics",
  "Z GALLERIE??",
];

const GREY = "#CCC";
const GREY_LIGHT = "rgba(255, 255, 255, 0.4)";
const GREY_DIM = "#686868";

export const csvUploadStyles = {
  zone: {
    alignItems: "center",
    border: `2px dashed ${GREY}`,
    borderRadius: 20,
    display: "flex",
    flexDirection: "column",
    height: "100%",
    justifyContent: "center",
    padding: 20,
  },
  file: {
    background: "linear-gradient(to bottom, #EEE, #DDD)",
    borderRadius: 20,
    display: "flex",
    height: 120,
    width: 120,
    position: "relative",
    zIndex: 10,
    flexDirection: "column",
    justifyContent: "center",
  },
  info: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    paddingLeft: 10,
    paddingRight: 10,
  },
  size: {
    backgroundColor: GREY_LIGHT,
    borderRadius: 3,
    marginBottom: "0.5em",
    justifyContent: "center",
    display: "flex",
  },
  name: {
    backgroundColor: GREY_LIGHT,
    borderRadius: 3,
    fontSize: 12,
    marginBottom: "0.5em",
  },
  progressBar: {
    bottom: 14,
    position: "absolute",
    width: "100%",
    paddingLeft: 10,
    paddingRight: 10,
  },
  zoneHover: {
    borderColor: GREY_DIM,
  },
  default: {
    borderColor: GREY,
  },
  remove: {
    height: 23,
    position: "absolute",
    right: 6,
    top: 6,
    width: 23,
  },
};
